### ISSUE TITLE
Atomic mass unit

### ISSUE THREAD

**Issue by mateuszbaran** [sostock/UnitfulAtomic.jl#5]
Hi! Could you add atomic mass unit to this package: https://en.wikipedia.org/wiki/Dalton_(unit) ? Thanks!

**Comment by sostock** [comment]
Hi! The atomic mass unit is already a part of Unitful.jl (where it’s simply called `u`):
```julia
julia> using Unitful

julia> uconvert(u"kg", 1u"u")
1.6605390666e-27 kg
```

**Comment by mateuszbaran** [comment]
Thanks, I didn't notice.
